### ISSUE TITLE
Should this be BaseCollection or Collection?

### ISSUE THREAD

**Issue by zack-carlson** [corcel/woocommerce#16]
https://github.com/corcel/woocommerce/blob/2a04d1123cfebdced47b8d3d13622e183f477ed0/src/Model/Product.php#L250

Product Attributes is expecting Collection and instead is provided BaseCollection - Does it matter which it gets and can I make a pull request? 

https://github.com/corcel/woocommerce/blob/2a04d1123cfebdced47b8d3d13622e183f477ed0/src/Model/ProductAttribute.php#L8

https://github.com/corcel/woocommerce/blob/2a04d1123cfebdced47b8d3d13622e183f477ed0/src/Model/ProductAttribute.php#L73

**Comment by Dartui** [comment]
As you can see in 11 and 14 line, there are two Collection classes used by this class:

https://github.com/corcel/woocommerce/blob/2a04d1123cfebdced47b8d3d13622e183f477ed0/src/Model/Product.php#L11-L14

Because of operations made on product attributes they are no more Eloquent Collection, but base Support Collection, thus why Illuminate\Support\Collection is renamed to BaseCollection and used as return type in getAttributesAttribute.

As far as I see there is no error here.

**Comment by zack-carlson** [comment]
`$product = new Product::find(2)`

`$product->attributes`

Provides an error: `must be an instance of Illuminate\Database\Eloquent\Collection, instance of Illuminate\Support\Collection given`.. which lets me think that Product should not use `getAttributesAttribute(): BaseCollection ` but `getAttributesAttribute(): Collection`

**Comment by Dartui** [comment]
Thanks for reporting this issue! In a minutes there will be tagged new release.
